fail_fast: true
default_stages: [commit]

repos:
  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py3-plus --py36-plus --py37-plus
        files: ^(src|tests)/
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: poetry run isort
        files: ^(src|tests)/
        language: system
        types: [python]

      - id: black
        name: black
        entry: poetry run black
        files: ^(src|tests)/
        language: system
        types: [python]

      - id: flake8
        name: flake8
        entry: poetry run flake8
        files: ^(src|tests)/
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: poetry run mypy
        files: ^src/
        language: system
        types: [python]

      - id: pydocstyle
        name: pydocstyle
        entry: poetry run pydocstyle
        files: ^src/
        language: system
        types: [python]

      - id: test
        name: test
        entry: poetry run pytest tests/
        files: ^(src|tests)/
        language: system
        pass_filenames: false
        types: [python]
